default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: r5wa_development
  username: postgres
  password:

test:
  <<: *default
  database: r5wa_test
  username: postgres
  password:

production:
  <<: *default
  database: r5wa_production
